L20 framework
Lokideos/simpler pull request #1
Opened 2018-12-05 17:49 UTC by Lokideos

В рамах данного пул реквеста в фреймворке **Simpler** был реализован следующий функционал:

1) Была добавлена возможность рендеринга ответа в формате `plain`;
2) Была добавлена возможность добавлять статус HTTP-ответа в контроллерах;
3) Была добавлена возможность добавлять кастомные хэдеры в HTTP-ответ;
4) Был реализован механизм разбора get запросов на параметры для дальнейшего образения к базе данных для поиска по id;
5) Было реализовано возвращение пользователю HTTP-ответа со статусом 404, если пользователь посещал ресурс, который еще не создан в данном веб-приложении;
6) Был реализован логгер, логирующий информацию о HTTP-запросах и HTTP-ответах.

2018-12-08 13:43 UTC, psylone requested changes

2018-12-08 13:43 UTC, psylone commented on lib/simpler/application.rb
> +      @application_logger = ApplicationLogger.new(nil, logdev: File.expand_path("#{Simpler.root}/log/app.log", __dir__))
`ApplicationLogger` используется в качестве middleware для логирования запросов. Нормальная практика, если в приложении есть несколько логгеров. Если ты хочешь использовать логгер внутри приложения, будет лучше определить `@logger = Logger.new(<logdev>)` в конструкторе и сделать `attr_reader`.

2018-12-08 13:43 UTC, psylone commented on lib/simpler/application.rb
> +      @application_logger = ApplicationLogger.new(nil, logdev: File.expand_path("#{Simpler.root}/log/app.log", __dir__))
Кроме того, у тебя здесь подключаются все файлы из middleware хотя к логгеру по факту имеет отношение только один из них.

2018-12-08 13:43 UTC, psylone commented on lib/simpler/application.rb
> +      @application_logger.log_handler(controller, action)
Логгер установлен в качестве middleware, вызывать его явно не нужно.

2018-12-08 13:43 UTC, psylone commented on lib/simpler/application.rb
> +    rescue NoMethodError => e
Будет лучше проверять был ли найден роут, поскольку исключение `NoMethodError` может выкинуть другой код, не связанный с маршрутизацией запроса.

2018-12-08 13:43 UTC, psylone commented on lib/simpler/controller.rb
> +      setup_logger
Части с логгером здесь тоже лишние.

2018-12-08 13:43 UTC, psylone commented on lib/simpler/controller.rb
> +    def get_ids
Контроллер не должен знать о маршрутах, это обязанность роутера.

2018-12-08 13:43 UTC, psylone commented on lib/simpler/controller.rb
> +        ids = path.match(ID_TYPE_REGEXP).to_s[1..-1].split("/")
Имей в виду, что URL может быть произвольным. В нём может быть несколько роут параметров, и они не обязательно имеют числовое значение, например: `/user/:login/payments/:month/year/:year` (`/user/bob/payments/december/year/2018`). В результате разбора роут параметров у тебя должен получиться хэш: `{'login' => 'bob', 'month' => 'december', 'year' => '2018'}`.

2018-12-08 13:43 UTC, psylone commented on lib/simpler/controller.rb
> +      @request.env['simpler.status_code'] = status_code
Нет необходимости записывать статус ответа в `@request.env`.

2018-12-08 13:43 UTC, psylone commented on lib/simpler/router.rb
> +      id_path = path.gsub(ID_REGEXP, '/:id')
Параметр может называться как угодно.

2018-12-08 13:43 UTC, psylone commented on lib/simpler/router/route.rb
> +        @method == method && path.match("#{@path}\/?$")
Исходи из самого общего решения. Параметров в URL может быть несколько, они могут иметь произвольное название и значение.

2018-12-08 13:43 UTC, psylone commented on lib/simpler/view.rb
> +      setup_logger
Здесь также логгер избыточен. Он работает на уровне middleware.

2018-12-08 13:43 UTC, psylone commented on lib/simpler/view.rb
> +      if render_type
Постарайся разделить логику рендеринга между разными классами. Например, у тебя может быть 2 класса: `HTMLRenderer` и `PlainTextRenderer`. У каждого из них будет метод `render`. Тогда задача класса `View` в том чтобы выбрать правильный класс рендерера на основе `env` и делегировать ему вызов метода `render`.

2018-12-08 13:43 UTC, psylone commented on log/app.log
> +I, [2018-12-05T20:35:03.051498 #10411]  INFO -- : Request: GET /tests/1
Файл лога необходимо исключить из репозитория.

2018-12-08 13:43 UTC, psylone commented on middleware/logger.rb
> +    @app.call(env)
У тебя несколько нарушены границы применения middleware. Его суть в том что ты устанавливаешь некоторую логику которая автоматически будет работать между запросом клиента и приложением.

Иными словами, здесь тебе необходимо залогировать информацию запроса. Посмотри ещё раз скринкаст относительно того как вызывается цепочка middleware и само приложение. Это похоже на луковицу. В данном случае сначала вызывается вот этот метод `call` здесь. В нём ты вызываешь приложение, получаешь ответ в виде `[status, headers, body]` и дальше можешь что-то сделать с этим ответом при необходимости или просто вернуть его, тогда эти данные уйдут клиенту. Вместо приложения `@app.call(env)` у тебя мог быть вызов ещё одного класса middleware.

Таким образом, реквайрить логгер в классы фрэймворка не нужно. Вместо этого здесь ты должен сформировать сообщение для логгера и вывести его. Получится примерно так:

```ruby
def call(env)
  status, headers, body = @app.call(env)
  @logger.info(format_message(env))
  [status, headers, body]
end
```

2018-12-10 14:53 UTC, Lokideos commented on lib/simpler/application.rb
> +    rescue NoMethodError => e
@psylone через guard clause реализовал в итоге. Надеюсь, подойдет.

2018-12-10 17:01 UTC, Lokideos commented on lib/simpler/controller.rb
> +        ids = path.match(ID_TYPE_REGEXP).to_s[1..-1].split("/")
@psylone реализовать это было сильно сложнее, чем я думал xD

2018-12-10 22:16 UTC, Lokideos commented on lib/simpler/router/route.rb
> +        @method == method && path.match("#{@path}\/?$")
@psylone вроде, поправил в роутере

2018-12-12 12:06 UTC, Lokideos commented on lib/simpler/view.rb
> +      if render_type
@psylone у меня в итоге с `eval`  только получается т_т

2018-12-14 22:48 UTC, psylone approved these changes

2018-12-14 22:48 UTC, psylone commented on lib/simpler/application.rb
> +      return route_does_not_exist(env['PATH_INFO'][1..-1]) unless route
Хочется назвать это `not_found_response` )

2018-12-14 22:48 UTC, psylone commented on lib/simpler/application.rb
> +      return route_does_not_exist(env['PATH_INFO'][1..-1]) unless route
В таких ситуациях лучше передавать объект целиком и уже внутри метода работать с ним, то есть:

```ruby
return route_does_not_exist(env) unless route
```

2018-12-14 22:48 UTC, psylone commented on lib/simpler/application.rb
> +        ["Couldn't connect to the desired URL.\nResource '#{resource_name.upcase}' doesn't exist\n"]
Проще здесь вернуть такой URL как он пришёл без преобразований, учитывая что URL может не совпадать с именем ресурса.

2018-12-14 22:48 UTC, psylone commented on lib/simpler/controller.rb
> +      @response.status = status_code || 200
Думаю, ситуация когда в параметре придет `nil` маловероятна.

2018-12-14 22:48 UTC, psylone commented on lib/simpler/router.rb
> +      get_params(env)
Нет смысла определять выше значение для `env`, если ты передаешь `env` в аргументе метода. Будет лучше сразу внутри метода сделать что-то вроде:

```ruby
def get_params(env)
  env['params_stash'] ||= {}
end
```

2018-12-14 22:48 UTC, psylone commented on lib/simpler/view.rb
> +      default: "HTMLRenderer"
Ты можешь в качестве элемента указать константу класса, вместо строки: `{ plain: PlainTextRenderer }`, тогда `eval` не понадобится.

2018-12-14 22:48 UTC, psylone commented on middleware/logger.rb
> +                 "#{env["simpler.controller"].request.env['REQUEST_PATH']}" +
В случае когда маршрут не будет найден здесь будет ошибка, поскольку `env['simpler.controller']` не установлен.

2018-12-14 22:48 UTC, psylone commented on lib/simpler/controller.rb
> +    def set_params
Здесь мы не устанавливаем параметры, а наоборот читаем, поэтому лучше назвать метод `get_params`, или просто `params`.

2018-12-14 22:48 UTC, psylone commented on lib/simpler/controller.rb
> +      end
Неплохо также устанавливать заголовки автоматически в зависимости от типа ответа.

2018-12-14 22:48 UTC, psylone commented on lib/simpler/controller.rb
> +      if options.first.class.to_s == "String"
Ты можешь использовать метод `kind_of?`: `options.first.kind_of?(String)` или `case`:

```ruby
case options.first
when String
else
end
```

2018-12-14 22:48 UTC, psylone commented on lib/simpler/router.rb
> +      path_resources = path_resources.delete_if { |elem| path_resources.index(elem).odd? }
Не факт что параметры чередуются через один: `/tests/search/:query` вполне законный вариант.

2018-12-14 22:48 UTC, psylone commented on lib/simpler/router.rb
> +        return route.path if route_resources == path_resources
Задача поиска совпадения URL с роутами это задача класса `Route`, а не `Router`.

2018-12-14 22:48 UTC, psylone commented on lib/simpler/router.rb
> +      path_resources = path_resources.delete_if { |elem| path_resources.index(elem).odd? }
Тебе не обязательно удалять сегменты роута. Достаточно разбить роут и URL на сегменты по слэшу и проверить что каждый сегмент роута соответствует сегменту запроса URL. Если сегмент роута начинается с `:` значит это параметр и его сразу же при обходе сегментов роута можно добавить в хэш роут параметров.

2018-12-14 22:48 UTC, psylone commented on lib/simpler/router.rb
> +        return route.path if route_resources == path_resources
Если не будет совпадения, насколько я понимаю, вернётся массив (его возвращает `each`).

2018-12-16 22:09 UTC, Lokideos commented on lib/simpler/view.rb
> +      default: "HTMLRenderer"
@psylone да, точно)

2018-12-16 22:11 UTC, Lokideos commented on middleware/logger.rb
> +                 "#{env["simpler.controller"].request.env['REQUEST_PATH']}" +
@psylone поправлено

2020-09-05 13:02 UTC, merged